{% set version = "0.0.2" %}
{% set sha256 = "7b8f74ae8424edcb7b6b78c9b12a354ca5276cf22f4e3d4ad8343671f301d8e6" %}
{% set user = "FloWuenne" %}

package:
  name: {{ mindagap }}
  version: {{ version }}

source:
  url: https://github.com/FloWuenne/MindaGap/archive/refs/tags/0.0.2.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - python
  run:
  - scipy
  - numpy
  - matplotlib
  - tifffile
  - cv2 
  - rich

test:
  commands:
    - python /mindagap/mindagap.py -v test

about:
  home: "https://github.com/ViriatoII/MindaGap"
  license: BSD 3-Clause License
  license_file: LICENSE
  summary: "Takes a single panorama image and fills the empty grid lines with neighbour-weighted values."
  doc_url: https://github.com/ViriatoII/MindaGap/blob/main/README.md

extra:
  recipe-maintainers:
    - FloWuenne
